# Generated by Django 5.0.2 on 2024-02-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voyage", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("program", "course", "content")},
        ),
    ]
